### ISSUE TITLE
L'utilisateur peut envoyer un fichier csv l'application retourne sans calcul à l'UI le fichier csv contenant les coordonnées

### ISSUE THREAD

**Issue by AntoineVen** [noebernigaud/ChemicalSimilarityViewer#11]
L'utilisateur peut envoyer un fichier csv représentant des molécules et l'application lui :
- renvoie un lien pour telecharger le fichier csv contenant les coordonnées
- affiche sous forme d'un tableau les coordonnées
Le backend ne calcule rien, il renvoie juste le fichier déjà préparé.

Comment tester;
L'utilisateur se connecte sur la page (maquette HTML)
Il renseigne le chemin du fichier csv: example20chemicals.csv
Il appuie sur submit
Le fichier est téléchargé dans le backend.
Un lien permet de telecharger le fichier example20chemicalsCoords.csv
Un tableau est affiché avec le contenu du fichier example20chemicalsCoords.csv

**Comment by FabriceCamilleri** [comment]
Temps necessaire pour développer cet user story:
- Noé: 4h
- Antoine: 6h

**Comment by FabriceCamilleri** [comment]
done
