### ISSUE TITLE
L'utilisateur a la représentation graphique des similarités entre les molécules

### ISSUE THREAD

**Issue by AntoineVen** [noebernigaud/ChemicalSimilarityViewer#12]
L'utilisateur a la représentation graphique des similarités entre les molécules.
Un graphique est affiché avec pour axes:
- axe 1: X_tsne_DiceDist
- axe 2: Y_tsne_DiceDis
Chaque molécule est représenté par un point. 
Quand l'utilisateur passe avec la souris sur un point, le nom de la molécule est affichée et les coordonnées. 
Comment tester:
- fichier [example20chemicals.csv](https://github.com/FabriceCamilleri/ChemicalSimilarityViewer/blob/main/csv_examples/example20chemicals.csv)
- on voit 20 points qui correspondent aux 20 molécules. 
- En survolant avec la souris chaque point on peut voir le nom correspondant et les coordonnées.

**Comment by FabriceCamilleri** [comment]
Temps necessaire:
- Antoine: 8h
- Noé: 6h

**Comment by noebernigaud** [comment]
done
