### ISSUE TITLE
L'utilisateur reçoit un message d'erreur quand le type de fichier envoyé est incorrect

### ISSUE THREAD

**Issue by FabriceCamilleri** [noebernigaud/ChemicalSimilarityViewer#20]
L'utilisateur reçoit un message d'erreur quand le type de fichier envoyé est incorrect (pas csv).
Comment tester:
l'utilisateur renseigne le fichier "[example20chemicals .txt](https://github.com/FabriceCamilleri/ChemicalSimilarityViewer/blob/main/csv_examples/example20chemicals%20.txt)"
L'UI affiche un message d'erreur "The file extension is not correct, please submit a .csv file".

**Comment by FabriceCamilleri** [comment]
Temps:
- Antoine: 1h
- Noé: 1h

**Comment by noebernigaud** [comment]
done
