### ISSUE TITLE
L'utilisateur peut envoyer un fichier dont les données sont séparées par des ;.

### ISSUE THREAD

**Issue by FabriceCamilleri** [noebernigaud/ChemicalSimilarityViewer#21]
L'utilisateur peut envoyer un fichier dont les données sont séparées par des ;. 
Comment tester:
- example20chemicalsSeparatedBySemiCol.csv

**Comment by FabriceCamilleri** [comment]
Temps:
- Noé: 1h
- Antoine: 1h

**Comment by noebernigaud** [comment]
done
