### ISSUE TITLE
L'utilisateur reçoit un message d'erreur quand le fichier ne peut pas être lu

### ISSUE THREAD

**Issue by FabriceCamilleri** [noebernigaud/ChemicalSimilarityViewer#22]
L'utilisateur reçoit un message d'erreur quand le fichier ne peut pas être lu (encodage)
L'application ne supporte que les formats ANSI et UTF8. 
Comment tester:
- l'utilisateur renseigne le fichier example20chemicalsWrongEncoding.csv
- un message d'erreur est affiché: "le format est du fichier n'est pas correct, merci d''utiliser le format Ansi ou UTF8"

**Comment by FabriceCamilleri** [comment]
OOM:
Noé 2h
Antoine 1h

**Comment by noebernigaud** [comment]
done: 1h
