### ISSUE TITLE
L'utilisateur peut voir la liste des smiles qui ne sont pas corrects

### ISSUE THREAD

**Issue by FabriceCamilleri** [noebernigaud/ChemicalSimilarityViewer#23]
L'utilisateur peut voir la liste des smiles qui ne sont pas corrects.
Comment tester:
- l'utilisateur renseigne example20chemicals_1KO.csv comme fichier
- il choisit tsne et cosine 
- le graphe est affiché
- sur le panneau de droite, en bas une nouvelle section 'non valid molecules" affiche le nom des molécules qui n'ont pas pu être converties en objet rdkit. 
-

**Comment by FabriceCamilleri** [comment]
OOM:
- Antoine: 2h
- Noé: 2h

**Comment by noebernigaud** [comment]
done: 2h
