### ISSUE TITLE
L'utilisateur peut choisir une a plusieurs distances.

### ISSUE THREAD

**Issue by FabriceCamilleri** [noebernigaud/ChemicalSimilarityViewer#24]
L'utilisateur peut choisir une a plusieurs distances: dice, tanimono, cosine en utilisant des checkboxs. 

Comment tester.
- l'utilisateur choisit un fichier
- il clique dans la partie distance: dice et tanimoto
- les coordonnées calculés sont tsne et umap avec dice et tanimoto.

**Comment by FabriceCamilleri** [comment]
OOM - sizing
- Noé: 6h
- Antoine: 5h

**Comment by noebernigaud** [comment]
done
