### ISSUE TITLE
L'utilisateur peut choisir tnse et / ou umap pour calculer les coordonnées. 

### ISSUE THREAD

**Issue by FabriceCamilleri** [noebernigaud/ChemicalSimilarityViewer#25]
L'utilisateur peut choisir tnse et / ou umap pour calculer les coordonnées en utilisant des checkboxs.

Comment tester.

l'utilisateur choisit un fichier
il clique dans la partie algo: umap
il choisit toutes les distances.
les coordonnées calculés umap avec dice, tanimoto et cosine.

**Comment by FabriceCamilleri** [comment]
OOM - sizing
- Noé: 3h
- Antoine: 3h

**Comment by noebernigaud** [comment]
done
