### ISSUE TITLE
L'utilisateur peut envoyer un fichier Excel

### ISSUE THREAD

**Issue by FabriceCamilleri** [noebernigaud/ChemicalSimilarityViewer#27]
L'utilisateur peut envoyer un fichier Excel avec les données sur la première ligne
Comment tester:
- l'utilisateur peut choisir le fichier example20chemicals .xlsx ou example20chemicals .xls
- l'application peut lire le fichier et affiche le tableau avec les données.

**Comment by FabriceCamilleri** [comment]
OOM:
- Noé: 2h
- Antoine: 3h

**Comment by noebernigaud** [comment]
done: 4h
