### ISSUE TITLE
L'utilisateur peut lancer le calcul des coordonnées pour un fichier qui prend tu temps.

### ISSUE THREAD

**Issue by FabriceCamilleri** [noebernigaud/ChemicalSimilarityViewer#30]
L'utilisateur peut lancer le calcul des coordonnées pour un fichier qui prend tu temps. L'UI prévient l'utilisateur que l'analyse est en cours. Quand l'analyse est finie, le résultat est affiché. 
Comment tester:
fichier: example500chemicalsWithCategory.csv

**Comment by FabriceCamilleri** [comment]
OOM:
- Noé: 10h
- Antoine:  6h

**Comment by noebernigaud** [comment]
done
