### ISSUE TITLE
L'utilisateur peut lancer le calcul des coordonnées, et revenir sur l'appli pour voir le resultat

### ISSUE THREAD

**Issue by FabriceCamilleri** [noebernigaud/ChemicalSimilarityViewer#35]
L'utilisateur peut lancer le calcul des coordonnées. Il ferme l'appli, et revient sur l'appli quelques minutes après. il peut retrouver le résultat. 
Comment tester: 
fichier: example19653chemicalsWithCategory.csv avec tsne. 
il ferme l'appli
il retourne sur l'appli 30 min après
une liste est affichée des travaux qui n'ont pas été vu. 
l'utilisateur clique sur son travail
le résultat est affiché. 
quand l'utilisateur revient sur l'appli un peu plus tard: la liste ne contient plus le travail qui a été vu auparavant.

**Comment by FabriceCamilleri** [comment]
OOM:
- Antoine: 6h
- Noé: 7h

**Comment by noebernigaud** [comment]
done 10h
