### ISSUE TITLE
L'utilisateur peut envoyer un fichier csv représentant des molécules et l'application lui renvoie le nombre de molécules dans le fichier.

### ISSUE THREAD

**Issue by AntoineVen** [noebernigaud/ChemicalSimilarityViewer#7]
- [x] #8
- [x] #9
- [x] #10

Comment le tester:
L'utilisateur se connecte sur la page (maquette HTML)
Il renseigne le chemin du fichier csv: example20chemicals.csv
Il appuie sur submit
Le fichier est téléchargé dans le backend. 
Le nombre de molécule est affiché: 20.

**Comment by FabriceCamilleri** [comment]
Temps necessaire pour développer cet user story: 
- Noé: 10h
- Antoine: 8h

**Comment by FabriceCamilleri** [comment]
Done.
